name: phorm
description: PHORM — a lightweight, type-safe, driver-agnostic ORM for Dart and Flutter.
version: 1.0.0
repository: https://github.com/interdev7/phorm
homepage: https://github.com/interdev7/phorm/tree/main/phorm
issue_tracker: https://github.com/interdev7/phorm/issues
license: MIT

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  phorm_annotations: ^1.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0

screenshots:
  - description: The PHORM package logo.
    path: screenshots/logo.png
