name: phorm_sqlite
description: The SQLite driver and connection manager implementation for the PHORM.
version: 1.2.0
repository: https://github.com/interdev7/phorm
homepage: https://github.com/interdev7/phorm/tree/main/packages/phorm_sqlite
issue_tracker: https://github.com/interdev7/phorm/issues
license: MIT

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  path: ^1.9.0
  path_provider: ^2.1.5
  phorm: ^1.2.0
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.0
  sqlite3_web: ^0.4.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  phorm_generator: ^1.2.0
  very_good_analysis: ^8.0.0

dependency_overrides:
  phorm:
    path: ../phorm
  phorm_generator:
    path: ../phorm_generator

screenshots:
  - description: The PHORM SQLite package logo.
    path: screenshots/logo.png
