name: phorm_mysql
description: >
  MySQL driver for the PHORM.
  Provides a PhormDatabase implementation backed by MySQL,
  including connection management, dialect support, and async query execution.
version: 1.1.0
repository: https://github.com/interdev7/phorm
homepage: https://github.com/interdev7/phorm/tree/main/packages/phorm_mysql
issue_tracker: https://github.com/interdev7/phorm/issues
license: MIT

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  phorm: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.15

screenshots:
  - description: The PHORM MySQL package logo.
    path: screenshots/logo.png
