import 'package:flutter_test/flutter_test.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';
import 'package:sqflow_core/sqflow_core.dart';

import 'models/user.dart';

void main() {
  setUpAll(() {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  });

  late DB db;

  setUp(() {
    db = DB(
      databaseName: ':memory:',
      version: 1,
      tables: [usersTable, ordersTable],
    );
  });

  tearDown(() async {
    await db.close();
  });

  test('Indices are created in the database', () async {
    final database = await db.database;

    // Check indices for 'users' table
    final userIndexes = await database.rawQuery(
        "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='users'");
    final userIndexNames = userIndexes.map((i) => i['name'] as String).toList();

    expect(userIndexNames, contains('users_email_idx'));
    expect(userIndexNames, contains('users_first_name_last_name_idx'));

    // Check index for 'orders' table
    final orderIndexes = await database.rawQuery(
        "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='orders'");
    final orderIndexNames =
        orderIndexes.map((i) => i['name'] as String).toList();

    expect(orderIndexNames, contains('orders_user_id_idx'));
  });

  test('Unique index prevents duplicate emails', () async {
    final userService = SqflowCore<User>(dbManager: db, table: usersTable);

    await userService.insertAsync(User(
      id: 'u1',
      firstName: 'John',
      lastName: 'Doe',
      email: 'john@example.com',
      phone: '123',
      gender: 'M',
      city: 'NY',
      country: 'USA',
    ));

    // Inserting another user with same email should fail
    expect(
        () => userService.insertAsync(User(
              id: 'u2',
              firstName: 'Jane',
              lastName: 'Doe',
              email: 'john@example.com',
              phone: '456',
              gender: 'F',
              city: 'LA',
              country: 'USA',
            )),
        throwsException);
  });

  test('Query plan uses index for JOIN relationship', () async {
    final database = await db.database;

    // We want to see if a query for orders by user_id uses the index
    final queryPlan = await database.rawQuery(
        "EXPLAIN QUERY PLAN SELECT * FROM orders WHERE user_id = 'u1'");

    // SQLite query plan output usually contains "SEARCH TABLE orders USING INDEX orders_user_id_idx"
    final planString = queryPlan.toString();
    expect(planString, contains('USING INDEX orders_user_id_idx'));
  });

  test('Complex relationship query plan uses indices', () async {
    final userService = SqflowCore<User>(dbManager: db, table: usersTable);

    // This will trigger the complex JOIN query
    // We can't easily capture the exact SQL generated by readAll without modifying the core,
    // but we can manually verify a similar JOIN query.

    final database = await db.database;
    final complexQueryPlan = await database.rawQuery('''
      EXPLAIN QUERY PLAN 
      SELECT users.*, orders.total
      FROM users 
      LEFT JOIN orders ON orders.user_id = users.id
      WHERE users.email = 'test@example.com'
    ''');

    final planString = complexQueryPlan.toString();

    // Should use unique index for users.email
    expect(planString, contains('USING INDEX users_email_idx'));
    
    // Should use index for orders.user_id
    expect(planString, contains('USING INDEX orders_user_id_idx'));
  });
}
